# Basic setup
#baseURL:        ''
baseURL:        'https://mimigasch.netlify.app'
languageCode:   'fr-FR'
title:          'mimigasch'

#publishDir:     '/home/lin/SyncFree/FreePublic/docker-compose-lamp/www/Desktop/public-michelle'
# Commenter obligatoirement pour netlify.

googleAnalytics: G-92V14G13XF

# Content setup
paginate:       9

# Parameter settings
params:
  author:       'Michelle Gasch'
  description:  'Plongez dans la tranquillité avec nos coloriages adultes zen. Libérez votre créativité et trouvez la sérénité intérieure. Découvrez notre collection apaisante dès maintenant!'
  email:        'mimigasch(signe bizarre)gmail.com'
  github:       'https://github.com/bibibricodeur'
